package com.example.moviesquiz.database.entities

import androidx.room.*
import androidx.room.ForeignKey.Companion.CASCADE

@Entity(foreignKeys = [ForeignKey(
    QuestionEntity::class,
    parentColumns = ["id"],
    childColumns = ["question_id"],
    onDelete = CASCADE
)],
    indices = [Index("question_id")]
)
data class AnswerEntity(
    @PrimaryKey(autoGenerate = true) val id: Long,
    val text: String,
    val isRight: Boolean,
    @ColumnInfo(name = "question_id") val questionId: String
)

fun getInitialAnswerEntities() = listOf(
    AnswerEntity(0, "ОХОТНИКИ НА ВЕДЬМ",  true, "1.1.1"),
    AnswerEntity(0,"ПОСЛЕДНИЙ ОХОТНИК НА ВЕДЬМ",  false, "1.1.1"),
    AnswerEntity(0,"СОКОЛИНЫЙ ГЛАЗ", false, "1.1.1"),
    AnswerEntity(0,"МСТИТЕЛИ", false, "1.1.1"),
    AnswerEntity(0,"ТЕМНЫЙ РЫЦАРЬ", true, "1.1.2"),
    AnswerEntity(0,"БЭТМЕН: НАЧАЛО",false, "1.1.2"),
    AnswerEntity(0,"ДЖОКЕР",  false, "1.1.2"),
    AnswerEntity(0,"ОТРЯД САМОУБИЙЦ",  false, "1.1.2"),
    AnswerEntity(0,"ДЖЕНТЛЬМЕНЫ",  true, "1.1.3"),
    AnswerEntity(0,"БОЛЬШОЙ КУШ",  false, "1.1.3"),
    AnswerEntity(0,"СЕМЬ ПСИХОПАТОВ",  false, "1.1.3"),
    AnswerEntity(0,"НАСТОЯЩИЙ ДЕТЕКТИВ",  false, "1.1.3"),
    AnswerEntity(0,"ПО СООБРАЖЕНИЯМ СОВЕСТИ", true, "1.1.4"),
    AnswerEntity(0,"СПАСТИ РЯДОВОГО РАЙАНА", false, "1.1.4"),
    AnswerEntity(0,"ЯРОСТЬ", false, "1.1.4"),
    AnswerEntity(0,"ТОНКАЯ КРАСНАЯ ЛИНИЯ", false, "1.1.4"),
    AnswerEntity(0,"ЗЕЛЕНАЯ КНИГА", true, "1.1.5"),
    AnswerEntity(0,"1+1", false, "1.1.5"),
    AnswerEntity(0,"КАПИТАН ФАНТАСТИК", false, "1.1.5"),
    AnswerEntity(0,"ЗЕЛЕНАЯ МИЛЯ", false, "1.1.5"),
    AnswerEntity(0,"ДЖАНГО ОСВОБОЖДЕННЫЙ", true, "1.1.6"),
    AnswerEntity(0,"ОМЕРЗИТЕЛЬНАЯ ВОСЬМЕРКА", false, "1.1.6"),
    AnswerEntity(0,"12 ЛЕТ РАБСТВА", false, "1.1.6"),
    AnswerEntity(0,"ЖЕЛЕЗНАЯ ХВАТКА", false, "1.1.6"),
    AnswerEntity(0,"FORD ПРОТИВ FERRARI", true, "1.1.7"),
    AnswerEntity(0,"ГОНКА", false, "1.1.7"),
    AnswerEntity(0,"ФОРСАЖ", false, "1.1.7"),
    AnswerEntity(0,"NEED FOR SPEED: ЖАЖДА СКОРОСТИ", false, "1.1.7"),
    AnswerEntity(0,"БЕССЛАВНЫЕ УБЛЮДКИ", true, "1.1.8"),
    AnswerEntity(0,"ОТСТУПНИКИ", false, "1.1.8"),
    AnswerEntity(0,"СЛАВНЫЕ ПАРНИ", false, "1.1.8"),
    AnswerEntity(0,"БЕШЕНЫЕ ПСЫ", false, "1.1.8"),
    AnswerEntity(0,"ЧЕРНЫЙ ЛЕБЕДЬ", true, "1.1.9"),
    AnswerEntity(0,"РЕКВИЕМ ПО МЕЧТЕ", false, "1.1.9"),
    AnswerEntity(0,"ЗА МНОЙ ПОСЛЕДНИЙ ТАНЕЦ", false, "1.1.9"),
    AnswerEntity(0,"ШАГ ВПЕРЕД", false, "1.1.9"),
    AnswerEntity(0,"ОНО", true, "1.1.10"),
    AnswerEntity(0,"ТЕМНАЯ БАШНЯ", false, "1.1.10"),
    AnswerEntity(0,"АСТРАЛ", false, "1.1.10"),
    AnswerEntity(0,"ЗАКЛЯТИЕ", false, "1.1.10"),
    AnswerEntity(0,"ОМЕРЗИТЕЛЬНАЯ ВОСЬМЕРКА", true, "1.1.11"),
    AnswerEntity(0,"ВЕЛИКОЛЕПНАЯ СЕМЕРКА", false, "1.1.11"),
    AnswerEntity(0,"БЫСТРЫЙ И МЕРТВЫЙ", false, "1.1.11"),
    AnswerEntity(0,"ХОРОШИЙ, ПЛОХОЙ, ЗЛОЙ", false, "1.1.11"),
    AnswerEntity(0,"НЕВИДИМАЯ СТОРОНА", true, "1.1.12"),
    AnswerEntity(0,"ТРЕНЕР КАРТЕР", false, "1.1.12"),
    AnswerEntity(0,"В ПОГОНЕ ЗА СЧАСТЬЕМ", false, "1.1.12"),
    AnswerEntity(0,"ВЕЛИКАН", false, "1.1.12"),
    AnswerEntity(0,"ДОСТАТЬ НОЖИ", true, "1.1.13"),
    AnswerEntity(0,"ДЖЕНТЛЬМЕНЫ", false, "1.1.13"),
    AnswerEntity(0,"УБИЙСТВО В ВОСТОЧНОМ ЭКСПРЕССЕ", false, "1.1.13"),
    AnswerEntity(0,"СМЕРТЬ НА НИЛЕ", false, "1.1.13"),
    AnswerEntity(0,"ИСХОДНЫЙ КОД", true, "1.1.14"),
    AnswerEntity(0,"ДЕЖАВЮ", false, "1.1.14"),
    AnswerEntity(0,"ГРАНЬ БУДУЩЕГО", false, "1.1.14"),
    AnswerEntity(0,"ДЕВУШКА В ПОЕЗДЕ", false, "1.1.14"),
    AnswerEntity(0,"ОТЕЛЬ «ГРАНД БУДАПЕШТ»", true, "1.1.15"),
    AnswerEntity(0,"ЧЕТЫРЕ КОМНАТЫ", false, "1.1.15"),
    AnswerEntity(0,"НИЧЕГО ХОРОШЕГО В ОТЕЛЕ «ЭЛЬ РОЯЛЬ»",  false, "1.1.15"),
    AnswerEntity(0,"ОТЕЛЬ «ЭЛЕОН»", false, "1.1.15"),
    AnswerEntity(0,"ВСЕ ВЕЗДЕ И СРАЗУ", true, "1.1.16"),
    AnswerEntity(0,"ПАРАЗИТЫ", false, "1.1.16"),
    AnswerEntity(0,"МАСТЕР Z: НАСЛЕДИЕ ИП МАНА", false, "1.1.16"),
    AnswerEntity(0,"БЕЗУМНО БОГАТЫЕ АЗИАТЫ", false, "1.1.16"),
    AnswerEntity(0,"ДЮНА", true, "1.1.17"),
    AnswerEntity(0,"ЗВЕЗДНЫЕ ВОЙНЫ", false, "1.1.17"),
    AnswerEntity(0,"ДЖОН КАРТЕР", false, "1.1.17"),
    AnswerEntity(0,"ХРОНИКИ РИДДИКА", false, "1.1.17"),
    AnswerEntity(0,"ДОМ GUCCI", true, "1.1.18"),
    AnswerEntity(0,"ВСЕ ДЕНЬГИ МИРА", false, "1.1.18"),
    AnswerEntity(0,"ЗВЕЗДА РОДИЛАСЬ", false, "1.1.18"),
    AnswerEntity(0,"АМЕРИКАНСКАЯ ИСТОРИЯ УЖАСОВ", false, "1.1.18"),
    AnswerEntity(0,"КРУЭЛЛА", true, "1.1.19"),
    AnswerEntity(0,"101 ДАЛМАТИНЕЦ", false, "1.1.19"),
    AnswerEntity(0,"МЕСТЬ ОТ КУТЮР", false, "1.1.19"),
    AnswerEntity(0,"ДЬЯВОЛ НОСИТ PRADA", false, "1.1.19"),
    AnswerEntity(0,"ДЭДПУЛ", true, "1.1.20"),
    AnswerEntity(0,"ЛЮДИ ИКС", false, "1.1.20"),
    AnswerEntity(0,"ЧЕЛОВЕК-ПАУК", false, "1.1.20"),
    AnswerEntity(0,"ПИПЕЦ", false, "1.1.20"),
    AnswerEntity(0,"БРАТ", true, "1.2.1"),
    AnswerEntity(0,"ЖМУРКИ",false, "1.2.1"),
    AnswerEntity(0,"БУМЕР", false, "1.2.1"),
    AnswerEntity(0,"БРАТЬЯ", false, "1.2.1"),
    AnswerEntity(0,"12", true, "1.2.2"),
    AnswerEntity(0,"12 РАЗГНЕВАННЫХ МУЖЧИН", false, "1.2.2"),
    AnswerEntity(0,"12 СТУЛЬЕВ", false, "1.2.2"),
    AnswerEntity(0,"12 ОБЕЗЬЯН", false, "1.2.2"),
    AnswerEntity(0,"ЛЕГЕНДА № 17", true, "1.2.3"),
    AnswerEntity(0,"Я — ЛЕГЕНДА", false, "1.2.3"),
    AnswerEntity(0,"ХОККЕЙ НАВСЕГДА", false, "1.2.3"),
    AnswerEntity(0,"БЫСТРЕЕ. ВЫШЕ. СИЛЬНЕЕ", false, "1.2.3"),
    AnswerEntity(0,"ПОСЛЕДНИЙ БОГАТЫРЬ", true, "1.2.4"),
    AnswerEntity(0,"НЕПОСЛУШНИК", false, "1.2.4"),
    AnswerEntity(0,"ХОЛОП", false, "1.2.4"),
    AnswerEntity(0,"МИСТЕР НОКАУТ", false, "1.2.4"),
    AnswerEntity(0,"ЧЕБУРАШКА", true, "1.2.5"),
    AnswerEntity(0,"ПРИКЛЮЧЕНИЯ ПАДДИНГТОНА", false, "1.2.5"),
    AnswerEntity(0,"КРОКОДИЛ ГЕНА", false, "1.2.5"),
    AnswerEntity(0,"ЧЕБУРАШКА ИДЕТ В ШКОЛУ", false, "1.2.5"),
    AnswerEntity(0,"ЖМУРКИ", true, "1.2.6"),
    AnswerEntity(0,"БУМЕР", false, "1.2.6"),
    AnswerEntity(0,"БРИГАДА", false, "1.2.6"),
    AnswerEntity(0,"БРАТ", false, "1.2.6"),
    AnswerEntity(0,"НЮРНБЕРГ", true, "1.2.7"),
    AnswerEntity(0,"БЕНДЕР: НАЧАЛО", false, "1.2.7"),
    AnswerEntity(0,"ПОДОЛЬСКИЕ КУРСАНТЫ", false, "1.2.7"),
    AnswerEntity(0,"ТРОЦКИЙ", false, "1.2.7"),
    AnswerEntity(0,"9 РОТА", true, "1.2.8"),
    AnswerEntity(0,"ГРОЗОВЫЕ ВОРОТА", false, "1.2.8"),
    AnswerEntity(0,"КАНДАГАР", false, "1.2.8"),
    AnswerEntity(0,"МЫ ИЗ БУДУЩЕГО", false, "1.2.8"),
    AnswerEntity(0,"НОЧНОЙ ДОЗОР", true, "1.2.9"),
    AnswerEntity(0,"УБОЙНАЯ СИЛА", false, "1.2.9"),
    AnswerEntity(0,"ОСОБО ОПАСЕН", false, "1.2.9"),
    AnswerEntity(0,"ЗА ЧАС ДО РАССВЕТА", false, "1.2.9"),
    AnswerEntity(0,"ЛЕД", true, "1.2.10"),
    AnswerEntity(0,"ЗОЛОТОЙ ЛЕД", false, "1.2.10"),
    AnswerEntity(0,"ЦЕПЛЯЯСЬ ЗА ЛЕД", false, "1.2.10"),
    AnswerEntity(0,"ПРИНЦЕССА ЛЬДА", false, "1.2.10"),
    AnswerEntity(0,"В АВГУСТЕ 44-ГО", true, "1.2.11"),
    AnswerEntity(0,"БРЕСТСКАЯ КРЕПОСТЬ", false, "1.2.11"),
    AnswerEntity(0,"НА БЕЗЫМЯННОЙ ВЫСОТЕ", false, "1.2.11"),
    AnswerEntity(0,"ДИВЕРСАНТ", false, "1.2.11"),
    AnswerEntity(0,"БАБУШКА ЛЕГКОГО ПОВЕДЕНИЯ", true, "1.2.12"),
    AnswerEntity(0,"ЛЕГОК НА ПОМИНЕ", false, "1.2.12"),
    AnswerEntity(0,"БАБУШКА", false, "1.2.12"),
    AnswerEntity(0,"ДОМ БОЛЬШОЙ МАМОЧКИ", false, "1.2.12"),
    AnswerEntity(0,"СТИЛЯГИ", true, "1.2.13"),
    AnswerEntity(0,"БРИОЛИН", false, "1.2.13"),
    AnswerEntity(0,"ЛА-ЛА ЛЕНД", false, "1.2.13"),
    AnswerEntity(0,"ВЕСТСАЙДСКАЯ ИСТОРИЯ", false, "1.2.13"),
    AnswerEntity(0,"ВИКИНГ", true, "1.2.14"),
    AnswerEntity(0,"ЛЕГЕНДА О КОЛОВРАТЕ", false, "1.2.14"),
    AnswerEntity(0,"СКИФ", false, "1.2.14"),
    AnswerEntity(0,"ВАРЯГ", false, "1.2.14"),
    AnswerEntity(0,"ВЫСОЦКИЙ. СПАСИБО, ЧТО ЖИВОЙ", true, "1.2.15"),
    AnswerEntity(0,"ЦОЙ", false, "1.2.15"),
    AnswerEntity(0,"ПОДДУБНЫЙ", false, "1.2.15"),
    AnswerEntity(0,"ДОВЛАТОВ", false, "1.2.15"),
    AnswerEntity(0,"ТУРЕЦКИЙ ГАМБИТ", true, "1.2.16"),
    AnswerEntity(0,"СТАТСКИЙ СОВЕТНИК", false, "1.2.16"),
    AnswerEntity(0,"АЗАЗЕЛЬ", false, "1.2.16"),
    AnswerEntity(0,"АДМИРАЛЪ", false, "1.2.16"),
    AnswerEntity(0,"ВИЙ", true, "1.2.17"),
    AnswerEntity(0,"ГОГОЛЬ. НАЧАЛО", false, "1.2.17"),
    AnswerEntity(0,"ДРАКУЛА", false, "1.2.17"),
    AnswerEntity(0,"ГОГОЛЬ. ВИЙ", false, "1.2.17"),
    AnswerEntity(0,"СЕСТРЕНКА", true, "1.2.18"),
    AnswerEntity(0,"СЕСТРЫ", false, "1.2.18"),
    AnswerEntity(0,"СЕСТРУХА", false, "1.2.18"),
    AnswerEntity(0,"СЕСТРА", false, "1.2.18"),
    AnswerEntity(0,"ЛЮБОВЬ-МОРКОВЬ", true, "1.2.19"),
    AnswerEntity(0,"МАЛЬЧИК В ДЕВОЧКЕ", false, "1.2.19"),
    AnswerEntity(0,"ЛЮБОВЬ В БОЛЬШОМ ГОРОДЕ", false, "1.2.19"),
    AnswerEntity(0,"ДЕВЯТЬ ЖИЗНЕЙ", false, "1.2.19"),
    AnswerEntity(0,"ЧЕРНАЯ МОЛНИЯ", true, "1.2.20"),
    AnswerEntity(0,"ДНЕВНОЙ ДОЗОР", false, "1.2.20"),
    AnswerEntity(0,"НА ИГРЕ", false, "1.2.20"),
    AnswerEntity(0,"СТРИТРЕЙСЕРЫ", false, "1.2.20"),
    AnswerEntity(0,"ДОМ ДРАКОНА", true, "1.3.1"),
    AnswerEntity(0,"ИГРА ПРЕСТОЛОВ", false, "1.3.1"),
    AnswerEntity(0,"ВИКИНГИ", false, "1.3.1"),
    AnswerEntity(0,"ВЕДЬМАК", false, "1.3.1"),
    AnswerEntity(0,"ВО ВСЕ ТЯЖКИЕ", true, "1.3.2"),
    AnswerEntity(0,"ЛУЧШЕ ЗВОНИТЕ СОЛУ", false, "1.3.2"),
    AnswerEntity(0,"ФАРГО", false, "1.3.2"),
    AnswerEntity(0,"ОЗАРК", false, "1.3.2"),
    AnswerEntity(0,"ДРУЗЬЯ",  true, "1.3.3"),
    AnswerEntity(0,"ОФИС", false, "1.3.3"),
    AnswerEntity(0,"ТЕОРИЯ БОЛЬШОГО ВЗРЫВА", false, "1.3.3"),
    AnswerEntity(0,"ДЕТСТВО ШЕЛДОНА", false, "1.3.3"),
    AnswerEntity(0,"КЛИНИКА", true, "1.3.4"),
    AnswerEntity(0,"ИНТЕРНЫ", false, "1.3.4"),
    AnswerEntity(0,"ДОКТОР ХАУС", false, "1.3.4"),
    AnswerEntity(0,"СКОРАЯ ПОМОЩЬ", false, "1.3.4"),
    AnswerEntity(0,"ОТЧАЯННЫЕ ДОМОХОЗЯЙКИ", true, "1.3.5"),
    AnswerEntity(0,"СЕКС В ДРУГОМ ГОРОДЕ", false, "1.3.5"),
    AnswerEntity(0,"ЛЮБОВНИЦЫ", false, "1.3.5"),
    AnswerEntity(0,"СЕКС В БОЛЬШОМ ГОРОДЕ", false, "1.3.5"),
    AnswerEntity(0,"ЧЕМ МЫ ЗАНЯТЫ В ТЕНИ", true, "1.3.6"),
    AnswerEntity(0,"РЕАЛЬНЫЕ УПЫРИ", false, "1.3.6"),
    AnswerEntity(0,"ВАМПИРЫ СРЕДНЕЙ ПОЛОСЫ", false, "1.3.6"),
    AnswerEntity(0,"ДНЕВНИКИ ВАМПИРА", false, "1.3.6"),
    AnswerEntity(0,"ТАЙНЫ СЛЕДСТВИЯ", true, "1.3.7"),
    AnswerEntity(0,"МАСТЕР И МАРГАРИТА", false, "1.3.7"),
    AnswerEntity(0,"УНЕСЕННЫЕ ВЕТРОМ", false, "1.3.7"),
    AnswerEntity(0,"ПОЮЩИЕ В ТЕРНОВНИКЕ", false, "1.3.7"),
    AnswerEntity(0,"ОЧЕНЬ СТРАННЫЕ ДЕЛА", true, "1.3.8"),
    AnswerEntity(0,"ОНО", false, "1.3.8"),
    AnswerEntity(0,"ТЬМА", false, "1.3.8"),
    AnswerEntity(0,"КАСЛ-РОК", false, "1.3.8"),
    AnswerEntity(0,"СВЕРЪЕСТЕСТВЕННОЕ", true, "1.3.9"),
    AnswerEntity(0,"ТАЙНЫ СМОЛВИЛЯ", false, "1.3.9"),
    AnswerEntity(0,"ПАЦАНЫ", false, "1.3.9"),
    AnswerEntity(0,"УОКЕР", false, "1.3.9"),
    AnswerEntity(0,"СТРАШНЫЕ СКАЗКИ", true, "1.3.10"),
    AnswerEntity(0,"АМЕРИКАНСКАЯ ИСТОРИЯ УЖАСОВ", false, "1.3.10"),
    AnswerEntity(0,"АМЕРИКАНСКАЯ ИСТОРИЯ ПРЕСТУПЛЕНИЙ", false, "1.3.10"),
    AnswerEntity(0,"ЦИРК УРОДОВ", false, "1.3.10"),
    AnswerEntity(0,"КОРОЛЕВСКИЙ ГАМБИТ", true, "1.3.11"),
    AnswerEntity(0,"ЖЕРТВУЯ ПЕШКОЙ", false, "1.3.11"),
    AnswerEntity(0,"ШАХМАТИСТ", false, "1.3.11"),
    AnswerEntity(0,"ХОД КОРОЛЕВЫ", false, "1.3.11"),
    AnswerEntity(0,"ОТЕЛЬ «ЭЛЕОН»", true, "1.3.12"),
    AnswerEntity(0,"ГРАНД", false, "1.3.12"),
    AnswerEntity(0,"КУХНЯ", false, "1.3.12"),
    AnswerEntity(0,"ШЕФ", false, "1.3.12"),
    AnswerEntity(0,"БАНДЫ НЬЮ-ЙОРКА", true, "1.3.13"),
    AnswerEntity(0,"ОСТРЫЕ КОЗЫРЬКИ", false, "1.3.13"),
    AnswerEntity(0,"СЫНЫ АНАРХИИ", false, "1.3.13"),
    AnswerEntity(0,"ОДНАЖДЫ В АМЕРИКЕ", false, "1.3.13"),
    AnswerEntity(0,"БОЛЬШАЯ МАЛЕНЬКАЯ ЛОЖЬ", true, "1.3.14"),
    AnswerEntity(0,"СЕКС В БОЛЬШОМ ГОРОДЕ", false, "1.3.14"),
    AnswerEntity(0,"И ПОВСЮДУ ТЛЕЮТ ПОЖАРЫ", false, "1.3.14"),
    AnswerEntity(0,"ПОЧЕМУ ЖЕНЩИНЫ УБИВАЮТ", false, "1.3.14"),
    AnswerEntity(0,"ИГРА НА ВЫЖИВАНИЕ", true, "1.3.15"),
    AnswerEntity(0,"ИГРА В КАЛЬМАРА", false, "1.3.15"),
    AnswerEntity(0,"ГОЛОДНЫЕ ИГРЫ", false, "1.3.15"),
    AnswerEntity(0,"ИГРА СМЕРТИ", false, "1.3.15"),
    AnswerEntity(0,"ИГРА ПРЕСТОЛОВ", true, "1.3.16"),
    AnswerEntity(0,"ЛЕГЕНДА ОБ ИСКАТЕЛЕ", false, "1.3.16"),
    AnswerEntity(0,"ВЕДЬМАК", false, "1.3.16"),
    AnswerEntity(0,"КАРНИВАЛ РОУ", false, "1.3.16"),
    AnswerEntity(0,"НУЛЕВОЙ ПАЦИЕНТ", true, "1.3.17"),
    AnswerEntity(0,"ЭПИДЕМИЯ", false, "1.3.17"),
    AnswerEntity(0,"ЧЕРНОБЫЛЬ", false, "1.3.17"),
    AnswerEntity(0,"5 ДНЕЙ ПОСЛЕ КАТАСТРОФЫ", false, "1.3.17"),
    AnswerEntity(0,"СПАРТАК: КРОВЬ И ПЕСОК", true, "1.3.18"),
    AnswerEntity(0,"ДОМ ПРЕСТОЛОВ", false, "1.3.18"),
    AnswerEntity(0,"ПОСЛЕДНЕЕ КОРОЛЕВСТВО", false, "1.3.18"),
    AnswerEntity(0,"ВИКИНГИ", false, "1.3.18"),
    AnswerEntity(0,"ЧЕРНАЯ ЛЮБОВЬ", true, "1.3.19"),
    AnswerEntity(0,"ПОСТУЧИСЬ В МОЮ ДВЕРЬ", false, "1.3.19"),
    AnswerEntity(0,"ВЕЛИКОЛЕПНЫЙ ВЕК", false, "1.3.19"),
    AnswerEntity(0,"ЗИМОРОДОК", false, "1.3.19"),
    AnswerEntity(0,"РУХНУВШИЕ НЕБЕСА", true, "1.3.20"),
    AnswerEntity(0,"КОЛОНИЯ", false, "1.3.20"),
    AnswerEntity(0,"ХОДЯЧИЕ МЕРТВЕЦЫ", false, "1.3.20"),
    AnswerEntity(0,"VИЗИТЕРЫ", false, "1.3.20"),
    AnswerEntity(0,"ТАЙНА КОКО", true, "1.4.1"),
    AnswerEntity(0,"ЭНКАНТО", false, "1.4.1"),
    AnswerEntity(0,"КНИГА ЖИЗНИ", false, "1.4.1"),
    AnswerEntity(0,"ЛУКА", false, "1.4.1"),
    AnswerEntity(0,"ДУША", true, "1.4.2"),
    AnswerEntity(0,"КАСПЕР", false, "1.4.2"),
    AnswerEntity(0,"ГОЛОВОЛОМКА", false, "1.4.2"),
    AnswerEntity(0,"СУПЕРСЕМЕЙКА", false, "1.4.2"),
    AnswerEntity(0,"ВВЕРХ", true, "1.4.3"),
    AnswerEntity(0,"ГАДКИЙ Я", false, "1.4.3"),
    AnswerEntity(0,"СЕЗОН ОХОТЫ", false, "1.4.3"),
    AnswerEntity(0,"ОБЛАЧНО, ВОЗМОЖНЫ ОСАДКИ В ВИДЕ ФРИКАДЕЛЕК", false, "1.4.3"),
    AnswerEntity(0,"ХОДЯЧИЙ ЗАМОК", true, "1.4.4"),
    AnswerEntity(0,"МОЙ СОСЕД ТОТОРО", false, "1.4.4"),
    AnswerEntity(0,"УНЕСЕННЫЕ ПРИЗРАКАМИ", false, "1.4.4"),
    AnswerEntity(0,"ДЕВОЧКА, ПОКОРИВШАЯ ВРЕМЯ", false, "1.4.4"),
    AnswerEntity(0,"ГОЛОВОЛОМКА", true, "1.4.5"),
    AnswerEntity(0,"ВОЛШЕБНЫЙ ПАРК ДЖУН", false, "1.4.5"),
    AnswerEntity(0,"МОЗГ НАПОПОЛАМ", false, "1.4.5"),
    AnswerEntity(0,"ЭМОДЖИ ФИЛЬМ", false, "1.4.5"),
    AnswerEntity(0,"РИК И МОРТИ", true, "1.4.6"),
    AnswerEntity(0,"ФУТУРАМА", false, "1.4.6"),
    AnswerEntity(0,"ЮЖНЫЙ ПАРК",  false, "1.4.6"),
    AnswerEntity(0,"ГРАВИТИ ФОЛЗ",  false, "1.4.6"),
    AnswerEntity(0,"РУСАЛОЧКА", true, "1.4.7"),
    AnswerEntity(0,"ЗОЛУШКА",  false, "1.4.7"),
    AnswerEntity(0,"ПРИНЦЕССА И ЛЯГУШКА", false, "1.4.7"),
    AnswerEntity(0,"СПЯЩАЯ КРАСАВИЦА", false, "1.4.7"),
    AnswerEntity(0,"МОАНА", true, "1.4.8"),
    AnswerEntity(0,"РАЛЬФ", false, "1.4.8"),
    AnswerEntity(0,"ПОКАХОНТАС", false, "1.4.8"),
    AnswerEntity(0,"ЛИЛО И СТИЧ", false, "1.4.8"),
    AnswerEntity(0,"ГАДКИЙ Я", true, "1.4.9"),
    AnswerEntity(0,"СУПЕРСЕМЕЙКА", false, "1.4.9"),
    AnswerEntity(0,"МИНЬОНЫ", false, "1.4.9"),
    AnswerEntity(0,"МЕГАМОЗГ", false, "1.4.9"),
    AnswerEntity(0,"МОНСТРЫ НА КАНИКУЛАХ", true, "1.4.10"),
    AnswerEntity(0,"КОРПОРАЦИЯ МОНСТРОВ", false, "1.4.10"),
    AnswerEntity(0,"АКАДЕМИЯ МОНСТРОВ", false, "1.4.10"),
    AnswerEntity(0,"МОНСТРЫ ПРОТИВ ПРИШЕЛЬЦЕВ", false, "1.4.10"),
    AnswerEntity(0,"КНИГА ДЖУНГЛЕЙ", true, "1.4.11"),
    AnswerEntity(0,"МАУГЛИ", false, "1.4.11"),
    AnswerEntity(0,"ТАРЗАН",  false, "1.4.11"),
    AnswerEntity(0,"БЕМБИ", false, "1.4.11"),
    AnswerEntity(0,"ШРЭК", true, "1.4.12"),
    AnswerEntity(0,"КОТ В САПОГАХ", false, "1.4.12"),
    AnswerEntity(0,"КРАСАВИЦА И ЧУДОВИЩЕ", false, "1.4.12"),
    AnswerEntity(0,"КУНГ-ФУ ПАНДА", false, "1.4.12"),
    AnswerEntity(0,"КАК ПРИРУЧИТЬ ДРАКОНА", true, "1.4.13"),
    AnswerEntity(0,"ХОРОШИЙ ДИНОЗАВР", false, "1.4.13"),
    AnswerEntity(0,"ОХОТНИКИ НА ДРАКОНОВ", false, "1.4.13"),
    AnswerEntity(0,"СЕРДЦЕ ДРАКОНА", false, "1.4.13"),
    AnswerEntity(0,"КУНГ-ФУ ПАНДА", true, "1.4.14"),
    AnswerEntity(0,"МАДАГАСКАР", false, "1.4.14"),
    AnswerEntity(0,"ЛЕСНАЯ БРАТВА", false, "1.4.14"),
    AnswerEntity(0,"ШРЭК", false, "1.4.14"),
    AnswerEntity(0,"ЗВЕРОПОЛИС", true, "1.4.15"),
    AnswerEntity(0,"ЗВЕРОПОЙ", false, "1.4.15"),
    AnswerEntity(0,"МАДАГАСКАР", false, "1.4.15"),
    AnswerEntity(0,"ТАЙНАЯ ЖИЗНЬ ДОМАШНИХ ЖИВОТНЫХ", false, "1.4.15"),
    AnswerEntity(0,"ЭНКАНТО", true, "1.4.16"),
    AnswerEntity(0,"МОАНА", false, "1.4.16"),
    AnswerEntity(0,"РАСПРЕКРАСНЫЙ ПРИНЦ", false, "1.4.16"),
    AnswerEntity(0,"ДАМБО", false, "1.4.16"),
    AnswerEntity(0,"ФИКСИКИ", true, "1.4.17"),
    AnswerEntity(0,"СМЕШАРИКИ", false, "1.4.17"),
    AnswerEntity(0,"БАРБОСКИНЫ", false, "1.4.17"),
    AnswerEntity(0,"ЦАРЕВНЫ", false, "1.4.17"),
    AnswerEntity(0,"СИМПСОНЫ", true, "1.4.18"),
    AnswerEntity(0,"ФУТУРАМА", false, "1.4.18"),
    AnswerEntity(0,"ГРИФФИНЫ", false, "1.4.18"),
    AnswerEntity(0,"АМЕРИКАНСКИЙ ПАПАША", false, "1.4.18"),
    AnswerEntity(0,"ХРАНИТЕЛИ СНОВ", true, "1.4.19"),
    AnswerEntity(0,"СЕКРЕТНАЯ СЛУЖБА САНТА-КЛАУСА", false, "1.4.19"),
    AnswerEntity(0,"ГОРОД ГЕРОЕВ", false, "1.4.19"),
    AnswerEntity(0,"РОЖДЕСТВЕНСКАЯ ИСТОРИЯ", false, "1.4.19"),
    AnswerEntity(0,"ИВАН ЦАРЕВИЧ И СЕРЫЙ ВОЛК", true, "1.4.20"),
    AnswerEntity(0,"ИЛЬЯ МУРОМЕЦ И СОЛОВЕЙ-РАЗБОЙНИК", false, "1.4.20"),
    AnswerEntity(0,"АЛЕША ПОПОВИЧ И ТУГАРИН ЗМЕЙ", false, "1.4.20"),
    AnswerEntity(0,"ДОБРЫНЯ НИКИТИЧ И ЗМЕЙ ГОРЫНЫЧ", false, "1.4.20"),
    AnswerEntity(0,"РАМИ МАЛЕК", true, "1.5.1"),
    AnswerEntity(0,"ФРЕДДИ МЕРКЬЮРИ", false, "1.5.1"),
    AnswerEntity(0,"САША БАРОН КОЭН", false, "1.5.1"),
    AnswerEntity(0,"БЕН СТИЛЛЕР", false, "1.5.1"),
    AnswerEntity(0,"ОРЛАНДО БЛУМ", true, "1.5.2"),
    AnswerEntity(0,"ГЕНРИ КАВИЛЛ", false, "1.5.2"),
    AnswerEntity(0,"ЛЮК ЭВАНС", false, "1.5.2"),
    AnswerEntity(0,"ДЖОННИ ДЕПП", false, "1.5.2"),
    AnswerEntity(0,"ДЭНИЭЛ РЭДКЛИФФ", true, "1.5.3"),
    AnswerEntity(0,"ЭЛАЙДЖА ВУД", false, "1.5.3"),
    AnswerEntity(0,"РУПЕРТ ГРИН", false, "1.5.3"),
    AnswerEntity(0,"ТОМ ФЕЛТОН", false, "1.5.3"),
    AnswerEntity(0,"АРНОЛЬД ШВАРЦЕНЕГГЕР", true, "1.5.4"),
    AnswerEntity(0,"СИЛЬВЕСТР СТАЛЛОНЕ", false, "1.5.4"),
    AnswerEntity(0,"ДОЛЬФ ЛУНДГРЕН", false, "1.5.4"),
    AnswerEntity(0,"ЖАН-КЛОД ВАН ДАММ", false, "1.5.4"),
    AnswerEntity(0,"ВУПИ ГОЛДБЕРГ", true, "1.5.5"),
    AnswerEntity(0,"ВИОЛА ДЭВИС", false, "1.5.5"),
    AnswerEntity(0,"ОКТАВИЯ СПЕНСЕР", false, "1.5.5"),
    AnswerEntity(0,"АНДЖЕЛА БАССЕТТ", false, "1.5.5"),
    AnswerEntity(0,"ПОЛ УОКЕР", true, "1.5.6"),
    AnswerEntity(0,"КОУДИ УОКЕР", false, "1.5.6"),
    AnswerEntity(0,"КАЛЕБ УОКЕР", false, "1.5.6"),
    AnswerEntity(0,"ЭНДРЮ УОКЕР", false, "1.5.6"),
    AnswerEntity(0,"ДЖЕННИФЕР ЛОПЕС", true, "1.5.7"),
    AnswerEntity(0,"ЕВА МЕНДЕС", false, "1.5.7"),
    AnswerEntity(0,"ПЕНЕЛОПА КРУС", false, "1.5.7"),
    AnswerEntity(0,"АЛИССА МИЛАНО", false, "1.5.7"),
    AnswerEntity(0,"ТОМ ХЭНКС", true, "1.5.8"),
    AnswerEntity(0,"ТИМ РОББИНС", false, "1.5.8"),
    AnswerEntity(0,"МЭТТЬЮ ПЕРРИ", false, "1.5.8"),
    AnswerEntity(0,"КОЛИН ХЭНКС", false, "1.5.8"),
    AnswerEntity(0,"КРИС ХЕМСВОРТ", true, "1.5.9"),
    AnswerEntity(0,"ЧАРЛИ ХАННЭМ", false, "1.5.9"),
    AnswerEntity(0,"РАЙАН ГОСЛИНГ", false, "1.5.9"),
    AnswerEntity(0,"РАЙАН РЕЙНОЛЬДС",false, "1.5.9"),
    AnswerEntity(0,"КЕЙТ БЕКИНСЕЙЛ", true, "1.5.10"),
    AnswerEntity(0,"КЕЙТ УИНСЛЕТ", false, "1.5.10"),
    AnswerEntity(0,"КЕЙТ БЛАНШЕТТ", false, "1.5.10"),
    AnswerEntity(0,"КЕЙТ ХАДСОН", false, "1.5.10"),
    AnswerEntity(0,"ТОМ ХИДДЛСТОН", true, "1.5.11"),
    AnswerEntity(0,"ТОМ ХАРДИ", false, "1.5.11"),
    AnswerEntity(0,"ТОМ ХОЛЛАНД", false, "1.5.11"),
    AnswerEntity(0,"ТОМ ХЭНКС", false, "1.5.11"),
    AnswerEntity(0,"ТОМ ХАРДИ", true, "1.5.12"),
    AnswerEntity(0,"ТОМ ХИДДЛСТОН", false, "1.5.12"),
    AnswerEntity(0,"ТОМ ХЭНКС", false, "1.5.12"),
    AnswerEntity(0,"ТОМ ХОЛЛАНД", false, "1.5.12"),
    AnswerEntity(0,"ЛИАМ НИСОН", true, "1.5.13"),
    AnswerEntity(0,"КЕВИН КОСТНЕР", false, "1.5.13"),
    AnswerEntity(0,"ХАРРИСОН ФОРД", false, "1.5.13"),
    AnswerEntity(0,"ДЕННИС КУЭЙД", false, "1.5.13"),
    AnswerEntity(0,"ЛЕОНАРДО ДИКАПРИО", true, "1.5.14"),
    AnswerEntity(0,"РОБЕРТ ДЕ НИРО", false, "1.5.14"),
    AnswerEntity(0,"БРЭД ПИТТ", false, "1.5.14"),
    AnswerEntity(0,"ДЖЕК НИКОЛСОН", false, "1.5.14"),
    AnswerEntity(0,"АЛЕКСАНДР ПЕТРОВ", true, "1.5.15"),
    AnswerEntity(0,"ДОМИНИК МОНАХЭН", false, "1.5.15"),
    AnswerEntity(0,"ШОН ЭШМОР", false, "1.5.15"),
    AnswerEntity(0,"ШОН ЭСТИН", false, "1.5.15"),
    AnswerEntity(0,"КИАНУ РИВЗ", true, "1.5.16"),
    AnswerEntity(0,"БЕН БАРНС", false, "1.5.16"),
    AnswerEntity(0,"АДАМ ДРАЙВЕР", false, "1.5.16"),
    AnswerEntity(0,"ПАВЕЛ ДУРОВ",false, "1.5.16"),
    AnswerEntity(0,"БИЛЛ МЮРРЕЙ",true, "1.5.17"),
    AnswerEntity(0,"РОБИН УИЛЬЯМС", false, "1.5.17"),
    AnswerEntity(0,"НИКОЛАЙ ФОМЕНКО", false, "1.5.17"),
    AnswerEntity(0,"ДЖЕЙМС БЕЛУШИ", false, "1.5.17"),
    AnswerEntity(0,"ДЭНИЭЛ КРЭЙГ", true, "1.5.18"),
    AnswerEntity(0,"ЭД ХАРРИС", false, "1.5.18"),
    AnswerEntity(0,"ДЖЕРЕМИ РЕННЕР", false, "1.5.18"),
    AnswerEntity(0,"ДЖЕЙСОН АЙЗЕКС", false, "1.5.18"),
    AnswerEntity(0,"УЭСЛИ СНАЙПС", true, "1.5.19"),
    AnswerEntity(0,"УИЛЛ СМИТ", false, "1.5.19"),
    AnswerEntity(0,"ТЕРРИ КРЮС", false, "1.5.19"),
    AnswerEntity(0,"ДЕНЗЕЛ ВАШИНГТОН", false, "1.5.19"),
    AnswerEntity(0,"БРЮС УИЛЛИС", true, "1.5.20"),
    AnswerEntity(0,"ДЖЕЙСОН СТЭЙТЕМ", false, "1.5.20"),
    AnswerEntity(0,"ВИН ДИЗЕЛЬ", false, "1.5.20"),
    AnswerEntity(0,"ДЖОН ТРАВОЛТА", false, "1.5.20"),
    AnswerEntity(0,"ЛЮБОВЬ И ГОЛУБИ", true, "1.6.1"),
    AnswerEntity(0,"МОСКВА СЛЕЗАМ НЕ ВЕРИТ", false, "1.6.1"),
    AnswerEntity(0,"ЛЕТЯТ ЖУРАВЛИ", false, "1.6.1"),
    AnswerEntity(0,"ВОКЗАЛ ДЛЯ ДВОИХ", false, "1.6.1"),
    AnswerEntity(0,"КРАСОТКА", true, "1.6.2"),
    AnswerEntity(0,"СБЕЖАВШАЯ НЕВЕСТА", false, "1.6.2"),
    AnswerEntity(0,"СВАДЬБА ЛУЧШЕГО ДРУГА", false, "1.6.2"),
    AnswerEntity(0,"ЖЕНИХ НАПРОКАТ", false, "1.6.2"),
    AnswerEntity(0,"КОШМАР НА УЛИЦЕ ВЯЗОВ", true, "1.6.3"),
    AnswerEntity(0,"КРИК", false, "1.6.3"),
    AnswerEntity(0,"ПЯТНИЦА 13-Е", false, "1.6.3"),
    AnswerEntity(0,"ВОССТАВШИЙ ИЗ АДА", false, "1.6.3"),
    AnswerEntity(0,"ФОРМУЛА ЛЮБВИ", true, "1.6.4"),
    AnswerEntity(0,"ОБЫКНОВЕННОЕ ЧУДО", false, "1.6.4"),
    AnswerEntity(0,"ЧАРОДЕИ", false, "1.6.4"),
    AnswerEntity(0,"ТОТ САМЫЙ МЮНХГАУЗЕН", false, "1.6.4"),
    AnswerEntity(0,"КРЕСТНЫЙ ОТЕЦ", true, "1.6.5"),
    AnswerEntity(0,"СОПРАНО", false, "1.6.5"),
    AnswerEntity(0,"ЛИЦО СО ШРАМОМ", false, "1.6.5"),
    AnswerEntity(0,"ОДНАЖДЫ В АМЕРИКЕ", false, "1.6.5"),
    AnswerEntity(0,"ШОУ ТРУМАНА", true, "1.6.6"),
    AnswerEntity(0,"ПЛЕЗАНТВИЛЬ", false, "1.6.6"),
    AnswerEntity(0,"МЕНЯЮЩИЕ РЕАЛЬНОСТЬ", false, "1.6.6"),
    AnswerEntity(0,"ВАНИЛЬНОЕ НЕБО", false, "1.6.6"),
    AnswerEntity(0,"МОЛЧАНИЕ ЯГНЯТ", true, "1.6.7"),
    AnswerEntity(0,"ГАННИБАЛ", false, "1.6.7"),
    AnswerEntity(0,"ЗОДИАК", false, "1.6.7"),
    AnswerEntity(0,"СЕМЬ", false, "1.6.7"),
    AnswerEntity(0,"ОХОТНИКИ ЗА ПРИВИДЕНИЯМИ", true, "1.6.8"),
    AnswerEntity(0,"ПРИЗРАЧНЫЙ ПАТРУЛЬ", false, "1.6.8"),
    AnswerEntity(0,"ЭВОЛЮЦИЯ", false, "1.6.8"),
    AnswerEntity(0,"ГРЕМЛИНЫ", false, "1.6.8"),
    AnswerEntity(0,"ЛИЦО СО ШРАМОМ", true, "1.6.9"),
    AnswerEntity(0,"ГАНГСТЕР", false, "1.6.9"),
    AnswerEntity(0,"СЛАВНЫЕ ПАРНИ", false, "1.6.9"),
    AnswerEntity(0,"КОКАИН", false, "1.6.9"),
    AnswerEntity(0,"НАЗАД В БУДУЩЕЕ", true, "1.6.10"),
    AnswerEntity(0,"ЭФФЕКТ БАБОЧКИ", false, "1.6.10"),
    AnswerEntity(0,"ТРАССА 60", false, "1.6.10"),
    AnswerEntity(0,"МАШИНА ВРЕМЕНИ В ДЖАКУЗИ", false, "1.6.10"),
    AnswerEntity(0,"ГРЯЗНЫЕ ТАНЦЫ", true, "1.6.11"),
    AnswerEntity(0,"ШАГ ВПЕРЕД", false, "1.6.11"),
    AnswerEntity(0,"ДЕРЖИ РИТМ", false, "1.6.11"),
    AnswerEntity(0,"ЛАПОЧКА", false, "1.6.11"),
    AnswerEntity(0,"ПОЛИЦЕЙСКАЯ АКАДЕМИЯ", true, "1.6.12"),
    AnswerEntity(0,"ГОРЯЧИЕ ГОЛОВЫ", false, "1.6.12"),
    AnswerEntity(0,"ПОЛИЦЕЙСКИЕ БУДНИ", false, "1.6.12"),
    AnswerEntity(0,"ДОБРОВОЛЬЦЫ ПОНЕВОЛЕ", false, "1.6.12"),
    AnswerEntity(0,"БЕЛОЕ СОЛНЦЕ ПУСТЫНИ", true, "1.6.13"),
    AnswerEntity(0,"САХАРА", false, "1.6.13"),
    AnswerEntity(0,"ИНДИАНА ДЖОНС И ХРАМ СУДЬБЫ", false, "1.6.13"),
    AnswerEntity(0,"КИН-ДЗА-ДЗА", false, "1.6.13"),
    AnswerEntity(0,"КРОКОДИЛ ДАНДИ", true, "1.6.14"),
    AnswerEntity(0,"ЖЕМЧУЖИНА НИЛА", false, "1.6.14"),
    AnswerEntity(0,"ШЕСТЬ ДНЕЙ, СЕМ НОЧЕЙ", false, "1.6.14"),
    AnswerEntity(0,"АЛЛИГАТОР", false, "1.6.14"),
    AnswerEntity(0,"ЗИТА И ГИТА", true, "1.6.15"),
    AnswerEntity(0,"ТАНЦОР ДИСКО", false, "1.6.15"),
    AnswerEntity(0,"МЕКСИКАНСКИЕ ПРИКЛЮЧЕНИЯ", false, "1.6.15"),
    AnswerEntity(0,"СВАДЬБА В МАЛИНОВКЕ", false, "1.6.15"),
    AnswerEntity(0,"В ДЖАЗЕ ТОЛЬКО ДЕВУШКИ", true, "1.6.16"),
    AnswerEntity(0,"ПОЮЩИЕ ПОД ДОЖДЕМ", false, "1.6.16"),
    AnswerEntity(0,"КАСАБЛАНКА", false, "1.6.16"),
    AnswerEntity(0,"ДАВАЙТЕ ПОТАНЦУЕМ", false, "1.6.16"),
    AnswerEntity(0,"ЗАВТРАК У ТИФФАНИ", true, "1.6.17"),
    AnswerEntity(0,"РИМСКИЕ КАНИКУЛЫ", false, "1.6.17"),
    AnswerEntity(0,"УНЕСЕННЫЕ ВЕТРОМ", false, "1.6.17"),
    AnswerEntity(0,"МОЯ ПРЕКРАСНАЯ ЛЕДИ", false, "1.6.17"),
    AnswerEntity(0,"ЧУЖОЙ", true, "1.6.18"),
    AnswerEntity(0,"ЖИВОЕ", false, "1.6.18"),
    AnswerEntity(0,"ГРАВИТАЦИЯ", false, "1.6.18"),
    AnswerEntity(0,"ЛУНА 2112", false, "1.6.18"),
    AnswerEntity(0,"УКРОЩЕНИЕ СТРОПТИВОГО", true, "1.6.19"),
    AnswerEntity(0,"БЕЗУМНО ВЛЮБЛЕННЫЙ", false, "1.6.19"),
    AnswerEntity(0,"БЛЕФ", false, "1.6.19"),
    AnswerEntity(0,"СЕРАФИНО", false, "1.6.19"),
    AnswerEntity(0,"СЛУЖЕБНЫЙ РОМАН", true, "1.6.20"),
    AnswerEntity(0,"ИРОНИЯ СУДЬБЫ, ИЛИ С ЛЕГКИМ ПАРОМ!", false, "1.6.20"),
    AnswerEntity(0,"ИЩИТЕ ЖЕНЩИНУ", false, "1.6.20"),
    AnswerEntity(0,"ПОКРОВСКИЕ ВОРОТА", false, "1.6.20"),
    AnswerEntity(0,"СОННАЯ ЛОЩИНА", true, "2.1.1"),
    AnswerEntity(0,"ПРИБЫТИЕ", true, "2.1.2"),
    AnswerEntity(0,"ГЛАВНЫЙ ГЕРОЙ", true, "2.1.3"),
    AnswerEntity(0,"ПРИСЛУГА", true, "2.1.4"),
    AnswerEntity(0,"ЗОДИАК", true, "2.1.5"),
    AnswerEntity(0,"ВЕЛИКОЛЕПНАЯ СЕМЕРКА", true, "2.1.6"),
    AnswerEntity(0,"ВЕК АДАЛИН", true, "2.1.7"),
    AnswerEntity(0,"АРТИСТ", true, "2.1.8"),
    AnswerEntity(0,"СКРЫТЫЕ ФИГУРЫ", true, "2.1.9"),
    AnswerEntity(0,"ВЕЛИКИЙ УРАВНИТЕЛЬ", true, "2.1.10"),
    AnswerEntity(0,"БРАТЬЯ ГРИММ", true, "2.1.11"),
    AnswerEntity(0,"ЧУДО", true, "2.1.12"),
    AnswerEntity(0,"СПЛИТ", true, "2.1.13"),
    AnswerEntity(0,"БИТЛДЖУС", true, "2.1.14"),
    AnswerEntity(0,"ЕВРОТУР", true, "2.1.15"),
    AnswerEntity(0,"МАЛЕНЬКИЕ ЖЕНЩИНЫ", true, "2.1.16"),
    AnswerEntity(0,"АГЕНТ ЕВА", true, "2.1.17"),
    AnswerEntity(0,"ГЛАДИАТОР", true, "2.1.18"),
    AnswerEntity(0,"МАРСИАНИН", true, "2.1.19"),
    AnswerEntity(0,"ХРАНИТЕЛИ", true, "2.1.20"),
    AnswerEntity(0,"ДУРАК", true, "2.2.1"),
    AnswerEntity(0,"БОЙ С ТЕНЬЮ", true, "2.2.2"),
    AnswerEntity(0,"ЛЕВИАФАН", true, "2.2.3"),
    AnswerEntity(0,"ЭКИПАЖ", true, "2.2.4"),
    AnswerEntity(0,"ГЕОГРАФ ГЛОБУС ПРОПИЛ", true, "2.2.5"),
    AnswerEntity(0,"Я ХУДЕЮ", true, "2.2.6"),
    AnswerEntity(0,"МЫ ИЗ БУДУЩЕГО", true, "2.2.7"),
    AnswerEntity(0,"ТЕКСТ", true, "2.2.8"),
    AnswerEntity(0,"ВРЕМЯ ПЕРВЫХ", true, "2.2.9"),
    AnswerEntity(0,"НЕПОСЛУШНИК", true, "2.2.10"),
    AnswerEntity(0,"ДОКТОР ЛИЗА", true, "2.2.11"),
    AnswerEntity(0,"АДМИРАЛЪ", true, "2.2.12"),
    AnswerEntity(0,"БУМЕР", true, "2.2.13"),
    AnswerEntity(0,"ШИРЛИ-МЫРЛИ", true, "2.2.14"),
    AnswerEntity(0,"ОБИТАЕМЫЙ ОСТРОВ", true, "2.2.15"),
    AnswerEntity(0,"СУПЕРБОБРОВЫ", true, "2.2.16"),
    AnswerEntity(0,"ОСТРОВ", true, "2.2.17"),
    AnswerEntity(0,"ДЕВЯТАЕВ", true, "2.2.18"),
    AnswerEntity(0,"СИБИРСКИЙ ЦИРЮЛЬНИК", true, "2.2.19"),
    AnswerEntity(0,"ОН ДРАКОН", true, "2.2.20"),
    AnswerEntity(0,"ОФИС", true, "2.3.1"),
    AnswerEntity(0,"СОПРАНО", true, "2.3.2"),
    AnswerEntity(0,"МОЛОДОЙ ПАПА", true, "2.3.3"),
    AnswerEntity(0,"ШЕРЛОК", true, "2.3.4"),
    AnswerEntity(0,"ТРИГГЕР", true, "2.3.5"),
    AnswerEntity(0,"ЭНН", true, "2.3.6"),
    AnswerEntity(0,"ОТБРОСЫ", true, "2.3.7"),
    AnswerEntity(0,"ТЕД ЛАССО", true, "2.3.8"),
    AnswerEntity(0,"ГАННИБАЛ", true, "2.3.9"),
    AnswerEntity(0,"МЫСЛИТЬ КАК ПРЕСТУПНИК",true, "2.3.10"),
    AnswerEntity(0,"СТРЕЛА",true, "2.3.11"),
    AnswerEntity(0,"БРУКЛИН 9-9",true, "2.3.12"),
    AnswerEntity(0,"ОБМАНИ МЕНЯ",true, "2.3.13"),
    AnswerEntity(0,"РАССКАЗ СЛУЖАНКИ",true, "2.3.14"),
    AnswerEntity(0,"УЭНСДЭЙ",true, "2.3.15"),
    AnswerEntity(0,"БУМАЖНЫЙ ДОМ",true, "2.3.16"),
    AnswerEntity(0,"ТЕНЬ И КОСТЬ",true, "2.3.17"),
    AnswerEntity(0,"СЕСТРА РЭТЧЕД",true, "2.3.18"),
    AnswerEntity(0,"МАНДАЛОРЕЦ",true, "2.3.19"),
    AnswerEntity(0,"ПОЧКА",true, "2.3.20"),
    AnswerEntity(0,"ДЮЙМОВОЧКА", true, "2.4.1"),
    AnswerEntity(0,"ВОЛЬТ", true, "2.4.2"),
    AnswerEntity(0,"ЛИЛО И СТИЧ", true, "2.4.3"),
    AnswerEntity(0,"БАЛТО", true, "2.4.4"),
    AnswerEntity(0,"ГОРОД ГЕРОЕВ", true, "2.4.5"),
    AnswerEntity(0,"КОШМАР ПЕРЕД РОЖДЕСТВОМ", true, "2.4.6"),
    AnswerEntity(0,"УМКА", true, "2.4.7"),
    AnswerEntity(0,"РАЙЯ И ПОСЛЕДНИЙ ДРАКОН", true, "2.4.8"),
    AnswerEntity(0,"ЛИС И ПЕС", true, "2.4.9"),
    AnswerEntity(0,"КОРАЛИНА В СТРАНЕ КОШМАРОВ", true, "2.4.10"),
    AnswerEntity(0,"ЖИЛ-БЫЛ ПЕС", true, "2.4.11"),
    AnswerEntity(0,"ТРУП НЕВЕСТЫ", true, "2.4.12"),
    AnswerEntity(0,"АНАСТАСИЯ", true, "2.4.13"),
    AnswerEntity(0,"СЕМЕЙКА КРУДС", true, "2.4.14"),
    AnswerEntity(0,"ЭВЕРЕСТ", true, "2.4.15"),
    AnswerEntity(0,"СМОЛФУТ", true, "2.4.16"),
    AnswerEntity(0,"ЛЕДИ И БРОДЯГА", true, "2.4.17"),
    AnswerEntity(0,"ГРИФФИНЫ", true, "2.4.18"),
    AnswerEntity(0,"ЛЕГЕНДЫ НОЧНЫХ СТРАЖЕЙ", true, "2.4.19"),
    AnswerEntity(0,"ЧЕРНЫЙ ПЛАЩ", true, "2.4.20"),
    AnswerEntity(0,"МИЛЛА ЙОВОВИЧ", true, "2.5.1"),
    AnswerEntity(0,"ГАЛЬ ГАДОТ", true, "2.5.2"),
    AnswerEntity(0,"ВЕНСАН КАССЕЛЬ", true, "2.5.3"),
    AnswerEntity(0,"ШЕЙЛИН ВУДЛИ", true, "2.5.4"),
    AnswerEntity(0,"ДЖЕЙМС МАКЭВОЙ", true, "2.5.5"),
    AnswerEntity(0,"ЭДРИАН БРОУДИ", true, "2.5.6"),
    AnswerEntity(0,"МИККИ РУРК", true, "2.5.7"),
    AnswerEntity(0,"ХАРРИСОН ФОРД", true, "2.5.8"),
    AnswerEntity(0,"ВИН ДИЗЕЛЬ", true, "2.5.9"),
    AnswerEntity(0,"ДРЮ БЭРРИМОР", true, "2.5.10"),
    AnswerEntity(0,"ЛЕОНАРДО ДИКАПРИО", true, "2.5.11"),
    AnswerEntity(0,"ЛЮСИ ЛЬЮ", true, "2.5.12"),
    AnswerEntity(0,"ДУЭЙН ДЖОНСОН", true, "2.5.13"),
    AnswerEntity(0,"ХИТ ЛЕДЖЕР", true, "2.5.14"),
    AnswerEntity(0,"МЭЛ ГИБСОН", true, "2.5.15"),
    AnswerEntity(0,"ДЕНЗЕЛ ВАШИНГТОН", true, "2.5.16"),
    AnswerEntity(0,"КИРА НАЙТЛИ", true, "2.5.17"),
    AnswerEntity(0,"ДЖЕЙК ДЖИЛЛЕНХОЛ", true, "2.5.18"),
    AnswerEntity(0,"НАТАЛИ ПОРТМАН", true, "2.5.19"),
    AnswerEntity(0,"МОРГАН ФРИМАН", true, "2.5.20"),
    AnswerEntity(0,"КИН-ДЗА-ДЗА!", true, "2.6.1"),
    AnswerEntity(0,"КРОВАВЫЙ СПОРТ", true, "2.6.2"),
    AnswerEntity(0,"ТУТСИ", true, "2.6.3"),
    AnswerEntity(0,"НЕУЛОВИМЫЕ МСТИТЕЛИ", true, "2.6.4"),
    AnswerEntity(0,"РОККИ", true, "2.6.5"),
    AnswerEntity(0,"СИЯНИЕ", true, "2.6.6"),
    AnswerEntity(0,"ИНТЕРВЬЮ С ВАМПИРОМ", true, "2.6.7"),
    AnswerEntity(0,"РОБОКОП", true, "2.6.8"),
    AnswerEntity(0,"СМЕРТЕЛЬНОЕ ОРУЖИЕ", true, "2.6.9"),
    AnswerEntity(0,"ПОЕЗДКА В АМЕРИКУ", true, "2.6.10"),
    AnswerEntity(0,"ДОСПЕХИ БОГА", true, "2.6.11"),
    AnswerEntity(0,"ГОЛЫЙ ПИСТОЛЕТ", true, "2.6.12"),
    AnswerEntity(0,"ЧАРОДЕИ", true, "2.6.13"),
    AnswerEntity(0,"ДРОЖЬ ЗЕМЛИ", true, "2.6.14"),
    AnswerEntity(0,"ЗОЛУШКА", true, "2.6.15"),
    AnswerEntity(0,"ТАНГО И КЭШ", true, "2.6.16"),
    AnswerEntity(0,"ТЕРНЕР И ХУЧ", true, "2.6.17"),
    AnswerEntity(0,"ЭДВАРД РУКИ-НОЖНИЦЫ", true, "2.6.18"),
    AnswerEntity(0,"ДЖУМАНДЖИ", true, "2.6.19"),
    AnswerEntity(0,"ПРИКЛЮЧЕНИЯ ЭЛЕКТРОНИКА", true, "2.6.20"),
    AnswerEntity(0,"МАЛЫШ НА ДРАЙВЕ", true, "3.1.1"),
    AnswerEntity(0,"ЗАКОНОПОСЛУШНЫЙ ГРАЖДАНИН", true, "3.1.2"),
    AnswerEntity(0,"ЛУЛУ И БРИГГС", true, "3.1.3"),
    AnswerEntity(0,"КОМАНДА А", true, "3.1.4"),
    AnswerEntity(0,"ЦВЕТОК ПУСТЫНИ", true, "3.1.5"),
    AnswerEntity(0,"ПОЕЗД В ПУСАН", true, "3.1.6"),
    AnswerEntity(0,"Я ИДУ ИСКАТЬ", true, "3.1.7"),
    AnswerEntity(0,"ОДАРЕННАЯ", true, "3.1.8"),
    AnswerEntity(0,"САМЫЙ ПЬЯНЫЙ ОКРУГ В МИРЕ", true, "3.1.9"),
    AnswerEntity(0,"МОЙ ШПИОН", true, "3.1.10"),
    AnswerEntity(0,"ДЕНЬ КУРКА", true, "3.1.11"),
    AnswerEntity(0,"ПОЕЗД НА ЮМУ", true, "3.1.12"),
    AnswerEntity(0,"ШАЗАМ!", true, "3.1.13"),
    AnswerEntity(0,"ЖИВАЯ СТАЛЬ", true, "3.1.14"),
    AnswerEntity(0,"АННА", true, "3.1.15"),
    AnswerEntity(0,"ОХОТНИКИ ЗА РАЗУМОМ", true, "3.1.16"),
    AnswerEntity(0,"ВИКИ КРИСТИНА БАРСЕЛОНА", true, "3.1.17"),
    AnswerEntity(0,"МАЙОР ПЭЙН", true, "3.1.18"),
    AnswerEntity(0,"ХИЖИНА В ЛЕСУ", true, "3.1.19"),
    AnswerEntity(0,"МЕЧ КОРОЛЯ АРТУРА", true, "3.1.20"),
    AnswerEntity(0,"МИСТЕР НОКАУТ", true, "3.2.1"),
    AnswerEntity(0,"ПРИЗРАК", true, "3.2.2"),
    AnswerEntity(0,"ЛЕТЧИК", true, "3.2.3"),
    AnswerEntity(0,"МАМЫ", true, "3.2.4"),
    AnswerEntity(0,"МОНГОЛ", true, "3.2.5"),
    AnswerEntity(0,"СТАТСКИЙ СОВЕТНИК", true, "3.2.6"),
    AnswerEntity(0,"ОХОТА НА ПИРАНЬЮ", true, "3.2.7"),
    AnswerEntity(0,"ПАЛЬМА", true, "3.2.8"),
    AnswerEntity(0,"ПОДДУБНЫЙ", true, "3.2.9"),
    AnswerEntity(0,"ЛЕДОКОЛ", true, "3.2.10"),
    AnswerEntity(0,"ВОДИТЕЛЬ ДЛЯ ВЕРЫ", true, "3.2.11"),
    AnswerEntity(0,"СВОЛОЧИ", true, "3.2.12"),
    AnswerEntity(0,"БЕЗ МЕНЯ", true, "3.2.13"),
    AnswerEntity(0,"АНТИКИЛЛЕР", true, "3.2.14"),
    AnswerEntity(0,"АРИТМИЯ", true, "3.2.15"),
    AnswerEntity(0,"ТОНКАЯ ШТУЧКА", true, "3.2.16"),
    AnswerEntity(0,"КАНИКУЛЫ СТРОГОГО РЕЖИМА", true, "3.2.17"),
    AnswerEntity(0,"НА ОСТРИЕ", true, "3.2.18"),
    AnswerEntity(0,"ПОДОЛЬСКИЕ КУРСАНТЫ", true, "3.2.19"),
    AnswerEntity(0,"СЕРЕБРЯНЫЕ КОНЬКИ", true, "3.2.20"),
    AnswerEntity(0,"ЗАЩИЩАЯ ДЖЕЙКОБА", true, "3.3.1"),
    AnswerEntity(0,"АКАДЕМИЯ АМБРЕЛЛА", true, "3.3.2"),
    AnswerEntity(0,"РОДИНА", true, "3.3.3"),
    AnswerEntity(0,"КОРОЛЬ И ШУТ", true, "3.3.4"),
    AnswerEntity(0,"ДОКТОР КТО", true, "3.3.5"),
    AnswerEntity(0,"ОДНИ ИЗ НАС", true, "3.3.6"),
    AnswerEntity(0,"НАСТОЯЩИЙ ДЕТЕКТИВ", true, "3.3.7"),
    AnswerEntity(0,"БЛАГИЕ ЗНАМЕНИЯ", true, "3.3.8"),
    AnswerEntity(0,"ВЕЛИКАЯ", true, "3.3.9"),
    AnswerEntity(0,"ЭПИДЕМИЯ", true, "3.3.10"),
    AnswerEntity(0,"ПУАРО", true, "3.3.11"),
    AnswerEntity(0,"ОДНАЖДЫ В СКАЗКЕ", true, "3.3.12"),
    AnswerEntity(0,"ПОБЕГ", true, "3.3.13"),
    AnswerEntity(0,"СЫНЫ АНАРХИИ", true, "3.3.14"),
    AnswerEntity(0,"ЛЮПЕН", true, "3.3.15"),
    AnswerEntity(0,"КАРНИВАЛ РОУ", true, "3.3.16"),
    AnswerEntity(0,"ПАЦАНЫ", true, "3.3.17"),
    AnswerEntity(0,"ПРОПОВЕДНИК", true, "3.3.18"),
    AnswerEntity(0,"ДЖИННИ И ДЖОРДЖИЯ", true, "3.3.19"),
    AnswerEntity(0,"ТЬМА", true, "3.3.20"),
    AnswerEntity(0,"УЧЕНИК ЧУДОВИЩА", true, "3.4.1"),
    AnswerEntity(0,"РОБОТЫ", true, "3.4.2"),
    AnswerEntity(0,"АРКЕЙН", true, "3.4.3"),
    AnswerEntity(0,"РАНГО", true, "3.4.4"),
    AnswerEntity(0,"ДОМ", true, "3.4.5"),
    AnswerEntity(0,"ОСТРОВ СОБАК", true, "3.4.6"),
    AnswerEntity(0,"ДОМ-МОНСТР", true, "3.4.7"),
    AnswerEntity(0,"БАЛЕРИНА", true, "3.4.8"),
    AnswerEntity(0,"КАРЛИК НОС", true, "3.4.9"),
    AnswerEntity(0,"ЛОРАКС", true, "3.4.10"),
    AnswerEntity(0,"КОТЫ-АРИСТОКРАТЫ", true, "3.4.11"),
    AnswerEntity(0,"МОНСТР В ПАРИЖЕ", true, "3.4.12"),
    AnswerEntity(0,"ПОБЕГ ИЗ КУРЯТНИКА", true, "3.4.13"),
    AnswerEntity(0,"Я КРАСНЕЮ", true, "3.4.14"),
    AnswerEntity(0,"АИСТЫ", true, "3.4.15"),
    AnswerEntity(0,"ЗОЛОТАЯ АНТИЛОПА", true, "3.4.16"),
    AnswerEntity(0,"ЗЕМЛЯ ДО НАЧАЛА ВРЕМЕН", true, "3.4.17"),
    AnswerEntity(0,"ПЕСНЬ МОРЯ", true, "3.4.18"),
    AnswerEntity(0,"ЛЕГЕНДА О КОРРЕ", true, "3.4.19"),
    AnswerEntity(0,"АТАКА ТИТАНОВ", true, "3.4.20"),
    AnswerEntity(0,"АГЕНТЫ А.Н.К.Л.", true, "3.5.1"),
    AnswerEntity(0,"ТРОЯ", true, "3.5.2"),
    AnswerEntity(0,"МИР ЮРСКОГО ПЕРИОДА", true, "3.5.3"),
    AnswerEntity(0,"ОТРЯД САМОУБИЙЦ", true, "3.5.4"),
    AnswerEntity(0,"ОТ ЗАКАТА ДО РАССВЕТА", true, "3.5.5"),
    AnswerEntity(0,"ОДИН ДОМА", true, "3.5.6"),
    AnswerEntity(0,"ПОСЛЕЗАВТРА", true, "3.5.7"),
    AnswerEntity(0,"АЛАДДИН", true, "3.5.8"),
    AnswerEntity(0,"АВАТАР", true, "3.5.9"),
    AnswerEntity(0,"ВАРКРАФТ", true, "3.5.10"),
    AnswerEntity(0,"ИНТЕРСТЕЛЛАР", true, "3.5.11"),
    AnswerEntity(0,"ДЬЯВОЛ НОСИТ PRADA", true, "3.5.12"),
    AnswerEntity(0,"МАЛЬЧИШНИК В ВЕГАСЕ", true, "3.5.13"),
    AnswerEntity(0,"МЫ — МИЛЛЕРЫ", true, "3.5.14"),
    AnswerEntity(0,"БЕЗУМНЫЙ МАКС", true, "3.5.15"),
    AnswerEntity(0,"ИЛЛЮЗИЯ ОБМАНА", true, "3.5.16"),
    AnswerEntity(0,"ПЕРЛ-ХАРБОР", true, "3.5.17"),
    AnswerEntity(0,"КРИМИНАЛЬНОЕ ЧТИВО", true, "3.5.18"),
    AnswerEntity(0,"ПРЕСТИЖ", true, "3.5.19"),
    AnswerEntity(0,"ЗВЕЗДНЫЙ ПУТЬ", true, "3.5.20"),
    AnswerEntity(0,"ТЕХАССКАЯ РЕЗНЯ БЕНЗОПИЛОЙ", true, "3.6.1"),
    AnswerEntity(0,"КЛУБ ЗАВТРАК", true, "3.6.2"),
    AnswerEntity(0,"ДЖЕНТЛЬМЕНЫ УДАЧИ", true, "3.6.3"),
    AnswerEntity(0,"ИНОПЛАНЕТЯНИН", true, "3.6.4"),
    AnswerEntity(0,"МОРОЗКО", true, "3.6.5"),
    AnswerEntity(0,"НЕВЕЗУЧИЕ", true, "3.6.6"),
    AnswerEntity(0,"ГОРЕЦ", true, "3.6.7"),
    AnswerEntity(0,"АРМАГЕДДОН", true, "3.6.8"),
    AnswerEntity(0,"ДЕНЬ НЕЗАВИСИМОСТИ", true, "3.6.9"),
    AnswerEntity(0,"БЕЗ ЛИЦА",true, "3.6.10"),
    AnswerEntity(0,"УЖ КТО БЫ ГОВОРИЛ",true, "3.6.11"),
    AnswerEntity(0,"ФАКУЛЬТЕТ",true, "3.6.12"),
    AnswerEntity(0,"ВОДНЫЙ МИР",true, "3.6.13"),
    AnswerEntity(0,"СКОРОСТЬ",true, "3.6.14"),
    AnswerEntity(0,"СМЕРТЬ ЕЙ К ЛИЦУ",true, "3.6.15"),
    AnswerEntity(0,"ТЕЛОХРАНИТЕЛЬ",true, "3.6.16"),
    AnswerEntity(0,"БЕТХОВЕН",true, "3.6.17"),
    AnswerEntity(0,"КАСПЕР",true, "3.6.18"),
    AnswerEntity(0,"ДЖЕЙН ЭЙР",true, "3.6.19"),
    AnswerEntity(0,"ТРУДНЫЙ РЕБЕНОК",true, "3.6.20"),
    AnswerEntity(0,"ВОЙНА МИРОВ", true, "3.7.1"),
    AnswerEntity(0,"БЕГУЩИЙ В ЛАБИРИНТЕ", true, "3.7.2"),
    AnswerEntity(0,"ГОЛОДНЫЕ ИГРЫ", true, "3.7.3"),
    AnswerEntity(0,"ДРУГОЙ МИР", true, "3.7.4"),
    AnswerEntity(0,"МОРСКОЙ БОЙ", true, "3.7.5"),
    AnswerEntity(0,"СМЕРТЕЛЬНАЯ БИТВА", true, "3.7.6"),
    AnswerEntity(0,"ДРУЗЬЯ", true, "3.7.7"),
    AnswerEntity(0,"ЗАЧАРОВАННЫЕ", true, "3.7.8"),
    AnswerEntity(0,"ТРАНСФОРМЕРЫ", true, "3.7.9"),
    AnswerEntity(0,"ПАРК ЮРСКОГО ПЕРИОДА",true, "3.7.10"),
    AnswerEntity(0,"СИЯНИЕ",true, "3.7.11"),
    AnswerEntity(0,"ЗВЕЗДНЫЕ ВРАТА",true, "3.7.12"),
    AnswerEntity(0,"ВЫШКА",true, "3.7.13"),
    AnswerEntity(0,"СУДЬЯ ДРЕДД",true, "3.7.14"),
    AnswerEntity(0,"ТИХООКЕАНСКИЙ РУБЕЖ",true, "3.7.15"),
    AnswerEntity(0,"ВАН ХЕЛЬСИНГ",true, "3.7.16"),
    AnswerEntity(0,"ОБЛИВИОН",true, "3.7.17"),
    AnswerEntity(0,"ЛЕДЯНОЙ ДРАЙВ",true, "3.7.18"),
    AnswerEntity(0,"САЙЛЕНТ ХИЛЛ",true, "3.7.19"),
    AnswerEntity(0,"НОЙ",true, "3.7.20")
)
